from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
JWT_SECRET = os.getenv("JWT_SECRET")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")


SELLERCLOUD_BASE_URL = os.getenv("SELLERCLOUD_BASE_URL")
SELLERCLOUD_USERNAME = os.getenv("SELLERCLOUD_USERNAME")
SELLERCLOUD_PASSWORD = os.getenv("SELLERCLOUD_PASSWORD")